[package]
name = "prover_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "prover_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }
rayon = "1.10.0"
sha2 = "0.10.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
